language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script:
  - python manage.py development
  - python manage.py test
  - python run.py &  # start a Web server in the background
  - sleep 5 # give Web server some time to bind to sockets, etc

script:
  - nosetests
  - behave

after_success:
  - codecov

services:
  - cleardb
