language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - python run.py &  # start a Web server in the background
  - sleep 5 # give Web server some time to bind to sockets, etc

env:
  global:
    - DATABASE_URI='mysql+pymysql://root@localhost:3306/test'

script:
  - nosetests
  - behave

after_success:
  - codecov

services:
  - cleardb
