language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: 
  - psql -c 'create database orders_test;' -U postgres

script:
  - nosetests

after_success:
 - codecov

services:
  - postgresql
