language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: 
  - psql -c 'create database orders_test;' -U postgres
  - python server.py &  # start a Web server in the background
  - sleep 3 # give Web server some time to bind to sockets, etc


script:
  - nosetests
  - behave

after_success:
 - codecov

services:
  - postgresql
